# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18m8wdIUbA9afRJJgQu442Jt17mvVeXZk
"""

a=10
b=20
c=25
if a>b and a>c:
    print("a is a larger number")
elif b>a and b>c:
    print("b is a larger number")
else:
    print("c is a larger number")